# Generated by Django 2.0.6 on 2018-06-13 19:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('prefered_books', django.contrib.postgres.fields.jsonb.JSONField()),
                ('similar_books', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
