# Generated by Django 2.0.6 on 2018-06-13 19:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20180613_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='prefered_books',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='similar_books',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
