# Generated by Django 2.0.6 on 2018-06-14 17:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20180613_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='prefered_books',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='similar_books',
        ),
        migrations.AddField(
            model_name='usergroup',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
